# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def function2(self,password,name):
        self.passtxt = password
        self.username = name

        conn = sqlite3.connect("project")
        res = conn.execute("select * from users where username = ? and password = ?",(name,password))
        conn.commit()
        for i in res:
            self.uemail.setText(str(i[1]))
            self.uname.setText(str(i[2]))
            self.upass.setText(str(i[3]))
            self.ucpass.setText(str(i[4]))
            self.name.setText(str(i[2]))

    def enabling(self):
        self.uemail.setEnabled(True)
        self.upass.setEnabled(True)
        self.ucpass.setEnabled(True)


    def updateinfo(self):

        name = self.uname.text()
        email = self.uemail.text()
        password = self.upass.text()
        cpassword = self.ucpass.text()

        conn = sqlite3.connect("project")
        res = conn.execute("update users set email = ?, password = ?, confirm_password =? where username = ?",(email,password,cpassword,name))
        msg = QMessageBox()
        msg.setWindowTitle("Leaf Restaurant!")
        msg.setText("Successfully updated!")
        msg.setIcon(QMessageBox.Warning)
        x = msg.exec_()
        conn.commit()
        self.uemail.setEnabled(False)
        self.uname.setEnabled(False)
        self.upass.setEnabled(False)
        self.ucpass.setEnabled(False)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 901))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 181, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/admin.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(330, 620, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"}\n"
"\n"
"")
        self.delete_2.setObjectName("delete_2")
        ########### ACTION ################
        self.delete_2.clicked.connect(self.updateinfo)

        ###################################
        self.edit = QtWidgets.QPushButton(self.centralwidget)
        self.edit.setGeometry(QtCore.QRect(60, 620, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit.setFont(font)
        self.edit.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"}\n"
"\n"
"")
        self.edit.setObjectName("edit")
        ########### ACTION ################
        self.edit.clicked.connect(self.enabling)

        ###################################
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 181, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/top-left.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 650, 181, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/corner.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(200, 220, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel{\n"
"color: #5F9EA0;\n"
"text-align: center;\n"
"}")
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.name_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(60, 320, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet("")
        self.name_2.setObjectName("name_2")
        self.name_3 = QtWidgets.QLabel(self.centralwidget)
        self.name_3.setGeometry(QtCore.QRect(60, 380, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_3.setFont(font)
        self.name_3.setStyleSheet("")
        self.name_3.setObjectName("name_3")
        self.name_4 = QtWidgets.QLabel(self.centralwidget)
        self.name_4.setGeometry(QtCore.QRect(60, 440, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_4.setFont(font)
        self.name_4.setStyleSheet("")
        self.name_4.setObjectName("name_4")
        self.name_5 = QtWidgets.QLabel(self.centralwidget)
        self.name_5.setGeometry(QtCore.QRect(60, 510, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_5.setFont(font)
        self.name_5.setStyleSheet("")
        self.name_5.setObjectName("name_5")
        self.uname = QtWidgets.QLineEdit(self.centralwidget)
        self.uname.setEnabled(False)
        self.uname.setGeometry(QtCore.QRect(280, 300, 271, 51))
        self.uname.setStyleSheet("QLineEdit{\n"
"border-radius : 1px;\n"
"border-bottom:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.uname.setAlignment(QtCore.Qt.AlignCenter)
        self.uname.setObjectName("uname")
        self.uemail = QtWidgets.QLineEdit(self.centralwidget)
        self.uemail.setEnabled(False)
        self.uemail.setGeometry(QtCore.QRect(280, 360, 271, 51))
        self.uemail.setStyleSheet("QLineEdit{\n"
"border-radius : 1px;\n"
"border-bottom:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.uemail.setAlignment(QtCore.Qt.AlignCenter)
        self.uemail.setObjectName("uemail")
        self.upass = QtWidgets.QLineEdit(self.centralwidget)
        self.upass.setEnabled(False)
        self.upass.setGeometry(QtCore.QRect(280, 420, 271, 51))
        self.upass.setStyleSheet("QLineEdit{\n"
"border-radius : 1px;\n"
"border-bottom:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.upass.setAlignment(QtCore.Qt.AlignCenter)
        self.upass.setObjectName("upass")
        self.ucpass = QtWidgets.QLineEdit(self.centralwidget)
        self.ucpass.setEnabled(False)
        self.ucpass.setGeometry(QtCore.QRect(280, 490, 271, 51))
        self.ucpass.setStyleSheet("QLineEdit{\n"
"border-radius : 1px;\n"
"border-bottom:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.ucpass.setAlignment(QtCore.Qt.AlignCenter)
        self.ucpass.setObjectName("ucpass")
        self.label.raise_()
        self.edit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.name.raise_()
        self.name_2.raise_()
        self.name_3.raise_()
        self.name_4.raise_()
        self.name_5.raise_()
        self.uname.raise_()
        self.uemail.raise_()
        self.upass.raise_()
        self.ucpass.raise_()
        self.delete_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.delete_2.setText(_translate("MainWindow", "Save"))
        self.edit.setText(_translate("MainWindow", "Edit"))
        self.name_2.setText(_translate("MainWindow", "Username :"))
        self.name_3.setText(_translate("MainWindow", "Email Address :"))
        self.name_4.setText(_translate("MainWindow", "Password :"))
        self.name_5.setText(_translate("MainWindow", "Confirm Password : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
