# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(241, 361)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(0, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:rgb(215,215,215,215);\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #BEBEBE, stop:1 #D7D7D7);\n"
"}")
        self.clear.setObjectName("clear")
        self.plusminus = QtWidgets.QPushButton(self.centralwidget)
        self.plusminus.setGeometry(QtCore.QRect(60, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusminus.setFont(font)
        self.plusminus.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:rgb(215,215,215,215);\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #BEBEBE, stop:1 #D7D7D7);\n"
"}")
        self.plusminus.setObjectName("plusminus")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(120, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.percent.setFont(font)
        self.percent.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:rgb(215,215,215,215);\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #BEBEBE, stop:1 #D7D7D7);\n"
"}")
        self.percent.setObjectName("percent")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(180, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.divide.setFont(font)
        self.divide.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:#4DD0E1;\n"
"color: white;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #79dce8, stop:1 #8ee1ec);\n"
"}")
        self.divide.setObjectName("divide")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(180, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:#4DD0E1;\n"
"color: white;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #79dce8, stop:1 #8ee1ec);\n"
"}")
        self.multiply.setObjectName("multiply")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(60, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eight.setFont(font)
        self.eight.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.eight.setObjectName("eight")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(0, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seven.setFont(font)
        self.seven.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.seven.setObjectName("seven")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(120, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nine.setFont(font)
        self.nine.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.nine.setObjectName("nine")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(180, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minus.setFont(font)
        self.minus.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:#4DD0E1;\n"
"color: white;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #79dce8, stop:1 #8ee1ec);\n"
"}")
        self.minus.setObjectName("minus")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(60, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.five.setFont(font)
        self.five.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.five.setObjectName("five")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(0, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.four.setFont(font)
        self.four.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.four.setObjectName("four")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(120, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.six.setFont(font)
        self.six.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.six.setObjectName("six")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(180, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add.setFont(font)
        self.add.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:#4DD0E1;\n"
"color: white;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #79dce8, stop:1 #8ee1ec);\n"
"}")
        self.add.setObjectName("add")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(60, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.two.setFont(font)
        self.two.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.two.setObjectName("two")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(0, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.one.setFont(font)
        self.one.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.one.setObjectName("one")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(120, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.three.setFont(font)
        self.three.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.three.setObjectName("three")
        self.decimal = QtWidgets.QPushButton(self.centralwidget)
        self.decimal.setGeometry(QtCore.QRect(120, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decimal.setFont(font)
        self.decimal.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:rgb(215,215,215,215);\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #BEBEBE, stop:1 #D7D7D7);\n"
"}")
        self.decimal.setObjectName("decimal")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(0, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zero.setFont(font)
        self.zero.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #dadbde, stop:1 #f6f7fa);\n"
"}")
        self.zero.setObjectName("zero")
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(180, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equals.setFont(font)
        self.equals.setStyleSheet("QPushButton{\n"
"\n"
"border: 1px solid gray;\n"
"background-color:#4DD0E1;\n"
"color: white;\n"
"\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color : qlineargradient(x1:0,y1:0,x2:0,y2:1, stop : 0 #79dce8, stop:1 #8ee1ec);\n"
"}")
        self.equals.setObjectName("equals")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.plusminus.setText(_translate("MainWindow", "+/-"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.multiply.setText(_translate("MainWindow", "X"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.six.setText(_translate("MainWindow", "6"))
        self.add.setText(_translate("MainWindow", "+"))
        self.two.setText(_translate("MainWindow", "2"))
        self.one.setText(_translate("MainWindow", "1"))
        self.three.setText(_translate("MainWindow", "3"))
        self.decimal.setText(_translate("MainWindow", "."))
        self.zero.setText(_translate("MainWindow", "0"))
        self.equals.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

