# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox




class Ui_Homewindow(object):
    food_list = []
    def __init__(self,window):
        self.window=window




    ################################################EXIT#################################


    def information(self,password,name):
        self.passtxt= password
        self.username = name

    def exit_action(self):
        # self.window.close()
        from ui_folder.admin import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.ui.function2(self.username, self.passtxt)
        # self.ui.updateinfo(self.username, self.passtxt)
        self.window.show()
        # box =QMessageBox()
        # box.setIcon(QMessageBox.Question)
        # box.setText("Are your sure you wanna exit?")
        # box.setWindowTitle("Message")
        # box.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        # box.setDefaultButton(QMessageBox.No)
        # buttonyes= box.button(QMessageBox.Yes)
        # buttonno = box.button(QMessageBox.No)
        # box.exec_()
        # if box.clickedButton() == buttonyes:
        #         Homewindow.destroy()

        ########################################################PRICE LIST #########################################
    def open_pricelist(self):

        from ui_folder.pricelist import Ui_PriceList
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PriceList()
        self.ui.setupUi(self.window)
        self.window.close()
        self.window.show()
    ######################################SIGN OUT##########################################################

    def openlogin_signout(self):
        self.window.close()
        from ui_folder.login import Ui_LoginPage
        self.window= QtWidgets.QDialog()
        self.ui =Ui_LoginPage(self.window)
        self.ui.setupUi(self.window)
        self.window.show()




    ################################################### ENABLING THE TEXTBOXES ##################################
                                        #########FOOD##########



    def cf1_function(self,cf1,tf1):
        if self.cf1.isChecked():
                self.tf1.setEnabled(True)
        else:
                self.tf1.setEnabled(False)
    def cf2_function(self,cf2,tf2):
        if self.cf2.isChecked():
                self.tf2.setEnabled(True)
                print("0")
        else:
                self.tf2.setEnabled(False)


    def cf3_function(self,cf3,tf3):
        if self.cf3.isChecked():
                self.tf3.setEnabled(True)
        else:
                self.tf3.setEnabled(False)
    def cf4_function(self,cf4,tf4):
        if self.cf4.isChecked():
                self.tf4.setEnabled(True)
        else:
                self.tf4.setEnabled(False)

                                ############ Drinks############

    def cd1_function(self, cd1, td1):
            if self.cd1.isChecked():
                    self.td1.setEnabled(True)
            else:
                    self.td1.setEnabled(False)

    def cd2_function(self, cd2, td2):
            if self.cd2.isChecked():
                    self.td2.setEnabled(True)
            else:
                    self.td2.setEnabled(False)

    def cd3_function(self, cd3, td3):
            if self.cd3.isChecked():
                    self.td3.setEnabled(True)
            else:
                    self.td3.setEnabled(False)

    def cd4_function(self, cd4, td4):
            if self.cd4.isChecked():
                    self.td4.setEnabled(True)
            else:
                    self.td4.setEnabled(False)
                                        ############ PIZZA ##############

    def cp1_function(self, cp1, tp1):
            if self.cp1.isChecked():
                    self.tp1.setEnabled(True)
            else:
                    self.tp1.setEnabled(False)

    def cp2_function(self, cp2, tp2):
            if self.cp2.isChecked():
                    self.tp2.setEnabled(True)
            else:
                    self.tp2.setEnabled(False)

    def cp3_function(self, cp3, tp3):
            if self.cp3.isChecked():
                    self.tp3.setEnabled(True)
            else:
                    self.tp3.setEnabled(False)

    def cp4_function(self, cp4, tp4):
            if self.cp4.isChecked():
                    self.tp4.setEnabled(True)
            else:
                    self.tp4.setEnabled(False)
                                                ############ DESERTS##############
    def cde1_function(self, cde1, tc1):
            if self.cde1.isChecked():
                    self.tc1.setEnabled(True)
            else:
                    self.tc1.setEnabled(False)

    def cde2_function(self, cde2, tc2):
            if self.cde2.isChecked():
                    self.tc2.setEnabled(True)
            else:
                    self.tc2.setEnabled(False)

    def cde3_function(self, cde3, tc3):
            if self.cde3.isChecked():
                    self.tc3.setEnabled(True)
            else:
                    self.tc3.setEnabled(False)

    def cde4_function(self, cde4, tc4):
            if self.cde4.isChecked():
                    self.tc4.setEnabled(True)
            else:
                    self.tc4.setEnabled(False)
                                        ######################### SHAKES ###################
    def cs1_function(self, cs1, ts1):
            if self.cs1.isChecked():
                    self.ts1.setEnabled(True)
            else:
                    self.ts1.setEnabled(False)

    def cs2_function(self, cs2, ts2):
            if self.cs2.isChecked():
                    self.ts2.setEnabled(True)
            else:
                    self.ts2.setEnabled(False)

    def cs3_function(self, cs3, ts3):
            if self.cs3.isChecked():
                    self.ts3.setEnabled(True)
            else:
                    self.ts3.setEnabled(False)

    def cs4_function(self, cs4, ts4):
            if self.cs4.isChecked():
                    self.ts4.setEnabled(True)
            else:
                    self.ts4.setEnabled(False)
            ########################################################### Database####################



    #################################################### Total #################################################
    def total_amount(self):

        item1 = float(self.tf1.text())
        item2 = float(self.tf2.text())
        # self.food_list.append("Bolanni")
        # self.food_list.append(item1)
        item3 = float(self.tf3.text())
        item4 = float(self.tf4.text())
        item5 = float(self.td1.text())
        item6 = float(self.td2.text())
        item7 = float(self.td3.text())
        item8 = float(self.td4.text())
        item9 = float(self.tp1.text())
        item10 =float(self.tp2.text())
        item11 = float(self.tp3.text())
        item12 = float(self.tp4.text())
        item13 = float(self.tc1.text())
        item14 = float(self.tc2.text())
        item15 = float(self.tc3.text())
        item16 = float(self.tc4.text())
        item17 = float(self.ts1.text())
        item18 = float(self.ts2.text())
        item19 = float(self.ts3.text())
        item20 = float(self.ts4.text())

        total = str((item1* 100)+(item2 *300)+(item3 * 350)+(item4*280)+ (item5 * 100)+(item6 * 80)+(item7 * 50) + (item8 * 60)+
                    (item13 * 300)+(item14 *320) +(item15 * 180) + (item16 *190)+ (item9 * 550) + (item10 * 500)+ (item11 * 450)+
                    (item12 * 150) + (item17 * 250)+ (item18 *180)+(item19* 210)+(item20 *200))

        self.totla_pay.setText(total)
        ####################################### RESET ##########################################

    def reset_button(self):
            ######################################### CHECKBOXES ##############################
            self.cd1.setChecked(False)
            self.cd2.setChecked(False)
            self.cd3.setChecked(False)
            self.cd4.setChecked(False)

            self.cf1.setChecked(False)
            self.cf2.setChecked(False)
            self.cf3.setChecked(False)
            self.cf4.setChecked(False)

            self.cp1.setChecked(False)
            self.cp2.setChecked(False)
            self.cp3.setChecked(False)
            self.cp4.setChecked(False)

            self.cs1.setChecked(False)
            self.cs2.setChecked(False)
            self.cs3.setChecked(False)
            self.cs4.setChecked(False)

            self.cde1.setChecked(False)
            self.cde2.setChecked(False)
            self.cde3.setChecked(False)
            self.cde4.setChecked(False)

            ################################# LINE EDIT ##############################################

            self.totla_pay.setText("0")

            ###################################### LINE EDITS##########################################

            self.tf1.setEnabled(False)
            self.tf1.setText("0")

            self.tf2.setEnabled(False)
            self.tf2.setText("0")

            self.tf3.setEnabled(False)
            self.tf3.setText("0")

            self.tf4.setEnabled(False)
            self.tf4.setText("0")

            self.td1.setEnabled(False)
            self.td1.setText("0")

            self.td2.setEnabled(False)
            self.td2.setText("0")

            self.td3.setEnabled(False)
            self.td3.setText("0")

            self.td4.setEnabled(False)
            self.td4.setText("0")

            self.tp1.setEnabled(False)
            self.tp1.setText("0")

            self.tp2.setEnabled(False)
            self.tp2.setText("0")

            self.tp3.setEnabled(False)
            self.tp3.setText("0")

            self.tp4.setEnabled(False)
            self.tp4.setText("0")

            self.tc1.setEnabled(False)
            self.tc1.setText("0")

            self.tc2.setEnabled(False)
            self.tc2.setText("0")

            self.tc3.setEnabled(False)
            self.tc3.setText("0")

            self.tc4.setEnabled(False)
            self.tc4.setText("0")

            self.ts1.setEnabled(False)
            self.ts1.setText("0")

            self.ts2.setEnabled(False)
            self.ts2.setText("0")

            self.ts3.setEnabled(False)
            self.ts3.setText("0")

            self.ts4.setEnabled(False)
            self.ts4.setText("0")
    ########################################################### RECEIPT ################################################
    def view_receipt(self):
        from ui_folder.receipt import Ui_receipt
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_receipt()
        self.ui.setupUi(self.window)
        self.ui.display(self.tf1.text(), self.tf2.text(),self.totla_pay.text(), self.tf3.text(), self.tf4.text(),
                        self.tc1.text(),self.tc2.text(), self.tc3.text(),self.tc4.text(), self.ts1.text(),self.ts2.text(),
                        self.ts3.text(),self.ts4.text(),self.tp1.text(),self.tp2.text(),self.tp3.text(),self.tp4.text(),
                        self.td1.text(),self.td2.text(),self.td3.text(),self.td4.text())
        # self.window.close()
        self.window.show()

    def setupUi(self, Homewindow):
        Homewindow.setObjectName("Homewindow")
        Homewindow.resize(1116, 903)
        self.centralwidget = QtWidgets.QWidget(Homewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 640, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 130, 101, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/SPAGHETTI.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 130, 101, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/DRINKS.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 130, 101, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../images/PIZZA.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.tf1 = QtWidgets.QLineEdit(self.centralwidget)
        self.tf1.setEnabled(False)
        self.tf1.setGeometry(QtCore.QRect(250, 230, 71, 31))
        self.tf1.setText("20")
        self.tf1.setStyleSheet("QLineEdit{\n"
"\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"border-radius: 15px;\n"
"}")
        self.tf1.setObjectName("tf1")
        self.tf2 = QtWidgets.QLineEdit(self.centralwidget)
        self.tf2.setEnabled(False)
        self.tf2.setGeometry(QtCore.QRect(250, 270, 71, 31))
        self.tf2.setText("10")
        self.tf2.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf2.setObjectName("tf2")
        self.tf3 = QtWidgets.QLineEdit(self.centralwidget)
        self.tf3.setEnabled(False)
        self.tf3.setGeometry(QtCore.QRect(250, 310, 71, 31))
        self.tf3.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf3.setObjectName("tf3")
        self.tf4 = QtWidgets.QLineEdit(self.centralwidget)
        self.tf4.setEnabled(False)
        self.tf4.setGeometry(QtCore.QRect(250, 350, 71, 31))
        self.tf4.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tf4.setObjectName("tf4")
        self.foodframe = QtWidgets.QFrame(self.centralwidget)
        self.foodframe.setGeometry(QtCore.QRect(70, 180, 271, 241))
        self.foodframe.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #4DD0E1;\n"
"}")
        self.foodframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe.setLineWidth(8)
        self.foodframe.setMidLineWidth(8)
        self.foodframe.setObjectName("foodframe")



        self.cf1 = QtWidgets.QCheckBox(self.foodframe)
        self.cf1.setGeometry(QtCore.QRect(20, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cf1.setFont(font)
        self.cf1.setObjectName("cf1")

        ###########################ACTION################
        self.cf1.stateChanged.connect(lambda:self.cf1_function(self.cf1,self.tf1))
        ################################################
        self.cf2 = QtWidgets.QCheckBox(self.foodframe)
        self.cf2.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cf2.setFont(font)
        self.cf2.setObjectName("cf2")
        ###########################ACTION################
        self.cf2.stateChanged.connect(lambda: self.cf2_function(self.cf2, self.tf2))
        ################################################
        self.cf3 = QtWidgets.QCheckBox(self.foodframe)
        self.cf3.setGeometry(QtCore.QRect(20, 140, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cf3.setFont(font)
        self.cf3.setObjectName("cf3")
        ###########################ACTION################
        self.cf3.stateChanged.connect(lambda: self.cf3_function(self.cf3, self.tf3))
        ################################################
        self.cf4 = QtWidgets.QCheckBox(self.foodframe)
        self.cf4.setGeometry(QtCore.QRect(20, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cf4.setFont(font)
        self.cf4.setObjectName("cf4")
        ###########################ACTION################
        self.cf4.stateChanged.connect(lambda: self.cf4_function(self.cf4, self.tf4))
        ################################################
        self.td4 = QtWidgets.QLineEdit(self.centralwidget)
        self.td4.setEnabled(False)
        self.td4.setGeometry(QtCore.QRect(610, 350, 71, 31))
        self.td4.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td4.setObjectName("td4")
        self.td2 = QtWidgets.QLineEdit(self.centralwidget)
        self.td2.setEnabled(False)
        self.td2.setGeometry(QtCore.QRect(610, 270, 71, 31))
        self.td2.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td2.setObjectName("td2")
        self.td1 = QtWidgets.QLineEdit(self.centralwidget)
        self.td1.setEnabled(False)
        self.td1.setGeometry(QtCore.QRect(610, 230, 71, 31))
        self.td1.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td1.setObjectName("td1")
        self.foodframe_2 = QtWidgets.QFrame(self.centralwidget)
        self.foodframe_2.setGeometry(QtCore.QRect(430, 180, 271, 241))
        self.foodframe_2.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #4DD0E1;\n"
"}")
        self.foodframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe_2.setLineWidth(8)
        self.foodframe_2.setMidLineWidth(8)
        self.foodframe_2.setObjectName("foodframe_2")
        self.cd1 = QtWidgets.QCheckBox(self.foodframe_2)
        self.cd1.setGeometry(QtCore.QRect(20, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cd1.setFont(font)
        self.cd1.setObjectName("cd1")
        ###########################ACTION################
        self.cd1.stateChanged.connect(lambda: self.cd1_function(self.cd1, self.td1))
        ################################################
        self.cd2 = QtWidgets.QCheckBox(self.foodframe_2)
        self.cd2.setGeometry(QtCore.QRect(20, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cd2.setFont(font)
        self.cd2.setObjectName("cd2")
        ###########################ACTION################
        self.cd2.stateChanged.connect(lambda: self.cd2_function(self.cd2, self.td2))
        ################################################
        self.cd4 = QtWidgets.QCheckBox(self.foodframe_2)
        self.cd4.setGeometry(QtCore.QRect(20, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cd4.setFont(font)
        self.cd4.setObjectName("cd4")
        ###########################ACTION################
        self.cd4.stateChanged.connect(lambda: self.cd4_function(self.cd4, self.td4))
        ################################################
        self.td3 = QtWidgets.QLineEdit(self.centralwidget)
        self.td3.setEnabled(False)
        self.td3.setGeometry(QtCore.QRect(610, 310, 71, 31))
        self.td3.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.td3.setObjectName("td3")
        self.tp1 = QtWidgets.QLineEdit(self.centralwidget)
        self.tp1.setEnabled(False)
        self.tp1.setGeometry(QtCore.QRect(960, 230, 71, 31))
        self.tp1.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp1.setObjectName("tp1")
        self.tp2 = QtWidgets.QLineEdit(self.centralwidget)
        self.tp2.setEnabled(False)
        self.tp2.setGeometry(QtCore.QRect(960, 270, 71, 31))
        self.tp2.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp2.setObjectName("tp2")
        self.foodframe_3 = QtWidgets.QFrame(self.centralwidget)
        self.foodframe_3.setGeometry(QtCore.QRect(780, 180, 271, 241))
        self.foodframe_3.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #4DD0E1;\n"
"}")
        self.foodframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe_3.setLineWidth(8)
        self.foodframe_3.setMidLineWidth(8)
        self.foodframe_3.setObjectName("foodframe_3")
        self.cp1 = QtWidgets.QCheckBox(self.foodframe_3)
        self.cp1.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cp1.setFont(font)
        self.cp1.setObjectName("cp1")
        ###########################ACTION################
        self.cp1.stateChanged.connect(lambda: self.cp1_function(self.cp1, self.tp1))
        ################################################
        self.cp2 = QtWidgets.QCheckBox(self.foodframe_3)
        self.cp2.setGeometry(QtCore.QRect(20, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cp2.setFont(font)
        self.cp2.setObjectName("cp2")
        ###########################ACTION################
        self.cp2.stateChanged.connect(lambda: self.cp2_function(self.cp2, self.tp2))
        ################################################
        self.cp3 = QtWidgets.QCheckBox(self.foodframe_3)
        self.cp3.setGeometry(QtCore.QRect(20, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cp3.setFont(font)
        self.cp3.setObjectName("cp3")
        ###########################ACTION################
        self.cp3.stateChanged.connect(lambda: self.cp3_function(self.cp3, self.tp3))
        ################################################
        self.cp4 = QtWidgets.QCheckBox(self.foodframe_3)
        self.cp4.setGeometry(QtCore.QRect(20, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cp4.setFont(font)
        self.cp4.setObjectName("cp4")
        ###########################ACTION################
        self.cp4.stateChanged.connect(lambda: self.cp4_function(self.cp4, self.tp4))
        ################################################
        self.tp4 = QtWidgets.QLineEdit(self.centralwidget)
        self.tp4.setEnabled(False)
        self.tp4.setGeometry(QtCore.QRect(960, 350, 71, 31))
        self.tp4.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp4.setObjectName("tp4")
        self.tp3 = QtWidgets.QLineEdit(self.centralwidget)
        self.tp3.setEnabled(False)
        self.tp3.setGeometry(QtCore.QRect(960, 310, 71, 31))
        self.tp3.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tp3.setObjectName("tp3")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -10, 1141, 911))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.background.setFont(font)
        self.background.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(940, 720, 171, 181))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../images/corner.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 171, 161))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../images/top-left.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.tc1 = QtWidgets.QLineEdit(self.centralwidget)
        self.tc1.setEnabled(False)
        self.tc1.setGeometry(QtCore.QRect(250, 550, 71, 31))
        self.tc1.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc1.setObjectName("tc1")
        self.tc2 = QtWidgets.QLineEdit(self.centralwidget)
        self.tc2.setEnabled(False)
        self.tc2.setGeometry(QtCore.QRect(250, 590, 71, 31))
        self.tc2.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc2.setObjectName("tc2")
        self.tc4 = QtWidgets.QLineEdit(self.centralwidget)
        self.tc4.setEnabled(False)
        self.tc4.setGeometry(QtCore.QRect(250, 670, 71, 31))
        self.tc4.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc4.setObjectName("tc4")
        self.foodframe_4 = QtWidgets.QFrame(self.centralwidget)
        self.foodframe_4.setGeometry(QtCore.QRect(70, 490, 271, 241))
        self.foodframe_4.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #4DD0E1;\n"
"}")
        self.foodframe_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe_4.setLineWidth(8)
        self.foodframe_4.setMidLineWidth(8)
        self.foodframe_4.setObjectName("foodframe_4")
        self.cde1 = QtWidgets.QCheckBox(self.foodframe_4)
        self.cde1.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cde1.setFont(font)
        self.cde1.setObjectName("cde1")
        ###########################ACTION################
        self.cde1.stateChanged.connect(lambda: self.cde1_function(self.cde1, self.tc1))
        ################################################
        self.cde2 = QtWidgets.QCheckBox(self.foodframe_4)
        self.cde2.setGeometry(QtCore.QRect(20, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cde2.setFont(font)
        self.cde2.setObjectName("cde2")
        ###########################ACTION################
        self.cde2.stateChanged.connect(lambda: self.cde2_function(self.cde2, self.tc2))
        ################################################
        self.cde3 = QtWidgets.QCheckBox(self.foodframe_4)
        self.cde3.setGeometry(QtCore.QRect(20, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cde3.setFont(font)
        self.cde3.setObjectName("cde3")
        ###########################ACTION################
        self.cde3.stateChanged.connect(lambda: self.cde3_function(self.cde3, self.tc3))
        ################################################
        self.cde4 = QtWidgets.QCheckBox(self.foodframe_4)
        self.cde4.setGeometry(QtCore.QRect(20, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cde4.setFont(font)
        self.cde4.setObjectName("cde4")
        ###########################ACTION################
        self.cde4.stateChanged.connect(lambda: self.cde4_function(self.cde4, self.tc4))
        ################################################
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 440, 101, 101))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../images/cake.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.tc3 = QtWidgets.QLineEdit(self.centralwidget)
        self.tc3.setEnabled(False)
        self.tc3.setGeometry(QtCore.QRect(250, 630, 71, 31))
        self.tc3.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.tc3.setObjectName("tc3")
        self.pricelist = QtWidgets.QPushButton(self.centralwidget)
        self.pricelist.setGeometry(QtCore.QRect(780, 490, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pricelist.setFont(font)
        self.pricelist.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.pricelist.setObjectName("pricelist")

        ####Action#########################################
        self.pricelist.clicked.connect(self.open_pricelist)

        ####################################################
        self.foodframe_5 = QtWidgets.QFrame(self.centralwidget)
        self.foodframe_5.setGeometry(QtCore.QRect(430, 490, 271, 241))
        self.foodframe_5.setStyleSheet(".QFrame{\n"
"border-radius: 10px;\n"
"border: 3px solid #4DD0E1;\n"
"}")
        self.foodframe_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodframe_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foodframe_5.setLineWidth(8)
        self.foodframe_5.setMidLineWidth(8)
        self.foodframe_5.setObjectName("foodframe_5")
        self.cs1 = QtWidgets.QCheckBox(self.foodframe_5)
        self.cs1.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cs1.setFont(font)
        self.cs1.setObjectName("cs1")
        ###########################ACTION################
        self.cs1.stateChanged.connect(lambda: self.cs1_function(self.cs1, self.ts1))
        ################################################
        self.cs2 = QtWidgets.QCheckBox(self.foodframe_5)
        self.cs2.setGeometry(QtCore.QRect(20, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cs2.setFont(font)
        self.cs2.setObjectName("cs2")
        ###########################ACTION################
        self.cs2.stateChanged.connect(lambda: self.cs2_function(self.cs2, self.ts2))
        ################################################
        self.cs3 = QtWidgets.QCheckBox(self.foodframe_5)
        self.cs3.setGeometry(QtCore.QRect(20, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cs3.setFont(font)
        self.cs3.setObjectName("cs3")
        ###########################ACTION################
        self.cs3.stateChanged.connect(lambda: self.cs3_function(self.cs3, self.ts3))
        ################################################
        self.ts1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ts1.setEnabled(False)
        self.ts1.setGeometry(QtCore.QRect(610, 550, 71, 31))
        self.ts1.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts1.setObjectName("ts1")
        self.ts3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ts3.setEnabled(False)
        self.ts3.setGeometry(QtCore.QRect(610, 630, 71, 31))
        self.ts3.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts3.setObjectName("ts3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(510, 440, 101, 101))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../images/shakes.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.ts2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ts2.setEnabled(False)
        self.ts2.setGeometry(QtCore.QRect(610, 590, 71, 31))
        self.ts2.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts2.setObjectName("ts2")
        self.ts4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ts4.setEnabled(False)
        self.ts4.setGeometry(QtCore.QRect(610, 670, 71, 31))
        self.ts4.setStyleSheet("QLineEdit{\n"
"border-radius : 15px;\n"
"border:3px solid #4DD0E1;\n"
"font: 14px gray;\n"
"padding-left: 5px;\n"
"}")
        self.ts4.setObjectName("ts4")
        self.receipt = QtWidgets.QPushButton(self.centralwidget)
        self.receipt.setGeometry(QtCore.QRect(780, 550, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.receipt.setFont(font)
        self.receipt.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")

###################################################################################

        self.tf1.setText("0")

        self.tf2.setText("0")

        self.tf3.setText("0")

        self.tf4.setText("0")

        self.td1.setText("0")

        self.td2.setText("0")
        self.td3.setText("0")
        self.td4.setText("0")

        self.tp1.setText("0")

        self.tp2.setText("0")

        self.tp3.setText("0")
        self.tp4.setText("0")
        self.tc1.setText("0")

        self.tc2.setText("0")
        self.tc3.setText("0")
        self.tc4.setText("0")
        self.ts1.setText("0")
        self.ts2.setText("0")
        self.ts3.setText("0")
        self.ts4.setText("0")
####################################################################################
        self.receipt.setObjectName("receipt")

        ####Action####
        self.receipt.clicked.connect(self.view_receipt)

        ##############
        self.total = QtWidgets.QPushButton(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(780, 610, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.total.setFont(font)
        self.total.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.total.setObjectName("total")
        ####Action####
        self.total.clicked.connect(self.total_amount)

        ##############
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(780, 670, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.reset.setFont(font)
        self.reset.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.reset.setObjectName("reset")

        ####Action####
        self.reset.clicked.connect(self.reset_button)

        ##############
        self.signout = QtWidgets.QPushButton(self.centralwidget)
        self.signout.setGeometry(QtCore.QRect(1010, 0, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.signout.setFont(font)
        self.signout.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-radius: 25px !important;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.signout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/sign_out_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signout.setIcon(icon)
        self.signout.setIconSize(QtCore.QSize(40, 40))
        self.signout.setObjectName("signout")
        ####Action##############################################
        self.signout.clicked.connect(self.openlogin_signout)

        ###########################################################

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1060, 0, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.exit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(35, 35))
        self.exit.setObjectName("exit")

        ####Action###################################
        self.exit.clicked.connect(self.exit_action)

        #############################################
        self.totla_pay = QtWidgets.QLineEdit(self.centralwidget)
        self.totla_pay.setGeometry(QtCore.QRect(430, 780, 281, 51))
        font = QtGui.QFont()
        font.setFamily("red")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.totla_pay.setFont(font)
        self.totla_pay.setStyleSheet("QLineEdit{\n"
"border-radius : 25px;\n"
"border:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.totla_pay.setObjectName("totla_pay")
        self.totla_pay.setText("0")
        self.cd3 = QtWidgets.QCheckBox(self.centralwidget)
        self.cd3.setGeometry(QtCore.QRect(450, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cd3.setFont(font)
        self.cd3.setObjectName("cd3")
        ###########################ACTION################
        self.cd3.stateChanged.connect(lambda: self.cd3_function(self.cd3, self.td3))
        ################################################
        self.cs4 = QtWidgets.QCheckBox(self.centralwidget)
        self.cs4.setGeometry(QtCore.QRect(450, 670, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cs4.setFont(font)
        self.cs4.setObjectName("cs4")
        ###########################ACTION################
        self.cs4.stateChanged.connect(lambda: self.cs4_function(self.cs4, self.ts4))
        ################################################
        self.background.raise_()
        self.foodframe_5.raise_()
        self.foodframe_4.raise_()
        self.label_8.raise_()
        self.foodframe_3.raise_()
        self.foodframe_2.raise_()
        self.foodframe.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.tf2.raise_()
        self.tf3.raise_()
        self.tf4.raise_()
        self.tf1.raise_()
        self.td4.raise_()
        self.td2.raise_()
        self.td1.raise_()
        self.td3.raise_()
        self.label_4.raise_()
        self.tp1.raise_()
        self.tp2.raise_()
        self.tp4.raise_()
        self.tp3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.tc1.raise_()
        self.tc2.raise_()
        self.tc4.raise_()
        self.label_10.raise_()
        self.tc3.raise_()
        self.pricelist.raise_()
        self.ts1.raise_()
        self.ts3.raise_()
        self.label_11.raise_()
        self.ts2.raise_()
        self.ts4.raise_()
        self.receipt.raise_()
        self.total.raise_()
        self.reset.raise_()
        self.signout.raise_()
        self.exit.raise_()
        self.totla_pay.raise_()
        self.cd3.raise_()
        self.cs4.raise_()
        Homewindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Homewindow)
        QtCore.QMetaObject.connectSlotsByName(Homewindow)

    def retranslateUi(self, Homewindow):
        _translate = QtCore.QCoreApplication.translate
        Homewindow.setWindowTitle(_translate("Homewindow", "MainWindow"))
        self.label_2.setText(_translate("Homewindow", "Welcome to the Leaf Restaurant Management System"))
        self.tf1.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf2.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf3.setPlaceholderText(_translate("Homewindow", "0"))
        self.tf4.setPlaceholderText(_translate("Homewindow", "0"))
        self.cf1.setText(_translate("Homewindow", "Boolani"))
        self.cf2.setText(_translate("Homewindow", "Qabuli"))
        self.cf3.setText(_translate("Homewindow", "Mantoo"))
        self.cf4.setText(_translate("Homewindow", "Chicken Karaiee"))
        self.td4.setPlaceholderText(_translate("Homewindow", "0"))
        self.td2.setPlaceholderText(_translate("Homewindow", "0"))
        self.td1.setPlaceholderText(_translate("Homewindow", "0"))
        self.cd1.setText(_translate("Homewindow", "Soda"))
        self.cd2.setText(_translate("Homewindow", "Pepsi"))
        self.cd4.setText(_translate("Homewindow", "Coca Cola"))
        self.td3.setPlaceholderText(_translate("Homewindow", "0"))
        self.tp1.setPlaceholderText(_translate("Homewindow", "0"))
        self.tp2.setPlaceholderText(_translate("Homewindow", "0"))
        self.cp1.setText(_translate("Homewindow", "Chicken Fajita"))
        self.cp2.setText(_translate("Homewindow", "Margherita"))
        self.cp3.setText(_translate("Homewindow", "Vegetable"))
        self.cp4.setText(_translate("Homewindow", "Chicken"))
        self.tp4.setPlaceholderText(_translate("Homewindow", "0"))
        self.tp3.setPlaceholderText(_translate("Homewindow", "0"))
        self.tc1.setPlaceholderText(_translate("Homewindow", "0"))
        self.tc2.setPlaceholderText(_translate("Homewindow", "0"))
        self.tc4.setPlaceholderText(_translate("Homewindow", "0"))
        self.cde1.setText(_translate("Homewindow", "Chocolate Cake"))
        self.cde2.setText(_translate("Homewindow", "Key Lime Pie"))
        self.cde3.setText(_translate("Homewindow", "Brownie"))
        self.cde4.setText(_translate("Homewindow", "Cheese Cake"))
        self.tc3.setPlaceholderText(_translate("Homewindow", "0"))
        self.pricelist.setText(_translate("Homewindow", "Price List"))
        self.cs1.setText(_translate("Homewindow", "Fruity Pebble"))
        self.cs2.setText(_translate("Homewindow", "Banana Cream"))
        self.cs3.setText(_translate("Homewindow", "Milkshake"))
        self.ts1.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts3.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts2.setPlaceholderText(_translate("Homewindow", "0"))
        self.ts4.setPlaceholderText(_translate("Homewindow", "0"))
        self.receipt.setText(_translate("Homewindow", "Generate Receipt"))
        self.total.setText(_translate("Homewindow", "Total"))
        self.reset.setText(_translate("Homewindow", "Reset"))
        self.totla_pay.setPlaceholderText(_translate("Homewindow", "Total value"))
        self.cd3.setText(_translate("Homewindow", "Sprite"))
        self.cs4.setText(_translate("Homewindow", "Banana shake"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Homewindow = QtWidgets.QMainWindow()
    ui = Ui_Homewindow(Homewindow)
    ui.setupUi(Homewindow)
    Homewindow.show()
    sys.exit(app.exec_())




