# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox




class Ui_LoginPage(object):
    def __init__(self,window):
        self.window=window
    ####switch to Sign up Page##############################################################################
    def openwindow_login(self):
        ###hides the previous window
        self.window.close()
        from ui_folder.signup import Ui_SignupPage
        self.window = QtWidgets.QDialog()
        self.ui = Ui_SignupPage(self.window)
        self.ui.setupUi(self.window)
        self.window.show()

    ################################login##############################################

    def loginmethod(self):
        conn = sqlite3.connect("project")
        name = self.username.text()
        password = self.passtxt.text()
        result = conn.execute('select * from users where username = ? and password = ?', (name, password))

        if (len(result.fetchall()) > 0) and name != "" and password != "":
            self.window.close()
            from ui_folder.homepage import Ui_Homewindow
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Homewindow(self.window)
            self.ui.setupUi(self.window)
            self.ui.information(self.username.text(), self.passtxt.text())
            self.window.show()
            # self.homepagewindow()
        elif name == 'admin' and password == 'admin':
            msg = QMessageBox()
            msg.setWindowTitle("Leaf Restaurant")
            msg.setText("Welcome Admiinistrator")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec_()
            self.window.close()
            from ui_folder.settings import Ui_settings
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_settings(self.window)
            self.ui.setupUi(self.window)
            # self.ui.information(self.username.text(), self.passtxt.text())
            self.window.show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Leaf Restaurant")
            msg.setText("User doesn't exist!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
#################SWITCH to homepage function ######################################

    # def homepagewindow(self):
    #     self.window.close()
    #     from ui_folder.homepage import Ui_Homewindow
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_Homewindow(self.window)
    #     self.ui.setupUi(self.window)
    #     ###hides the previous window
    #     self.window.show()

    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(644, 576)
        LoginPage.setStyleSheet("")
        self.icon = QtWidgets.QLabel(LoginPage)
        self.icon.setGeometry(QtCore.QRect(260, 130, 131, 131))
        self.icon.setStyleSheet("border-radius: 50%;")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../images/person.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.Background = QtWidgets.QLabel(LoginPage)
        self.Background.setGeometry(QtCore.QRect(0, 0, 651, 581))
        self.Background.setStyleSheet("")
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap("../images/Peach and Gray Watercolor Background Instagram Post (2) - Copy.png"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.username = QtWidgets.QLineEdit(LoginPage)
        self.username.setGeometry(QtCore.QRect(170, 290, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color: white;\n"
"border: 3px solid #4DD0E1;\n"
"border-radius: 25px;\n"
"padding: 10px;\n"
"font-size: 15px;\n"
"font-color:gray;\n"
"")
        self.username.setObjectName("username")
        self.passtxt = QtWidgets.QLineEdit(LoginPage)
        self.passtxt.setGeometry(QtCore.QRect(170, 360, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.passtxt.setFont(font)
        self.passtxt.setStyleSheet("background-color: white;\n"
"border: 3px solid #4DD0E1;\n"
"border-radius: 25px;\n"
"padding: 10px;\n"
"font-size: 15px;\n"
"font-color:gray;")
        self.passtxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passtxt.setObjectName("passtxt")
        self.loginbtn = QtWidgets.QPushButton(LoginPage)
        self.loginbtn.setGeometry(QtCore.QRect(360, 440, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginbtn.setFont(font)
        self.loginbtn.setAutoFillBackground(False)
        self.loginbtn.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"}\n"
"")
        self.loginbtn.setObjectName("loginbtn")

        ########### ACTION ################
        self.loginbtn.clicked.connect(self.loginmethod)

        ###################################

        self.signupbtn = QtWidgets.QPushButton(LoginPage)
        self.signupbtn.setGeometry(QtCore.QRect(170, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.signupbtn.setFont(font)
        self.signupbtn.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"}\n"
"\n"
"")
        self.signupbtn.setObjectName("signupbtn")
        ########### ACTION ################
        self.signupbtn.clicked.connect(self. openwindow_login)

        ###################################

        self.Background.raise_()
        self.icon.raise_()
        self.username.raise_()
        self.passtxt.raise_()
        self.loginbtn.raise_()
        self.signupbtn.raise_()

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Dialog"))
        self.username.setPlaceholderText(_translate("LoginPage", "Username"))
        self.passtxt.setPlaceholderText(_translate("LoginPage", "Password"))
        self.loginbtn.setText(_translate("LoginPage", "Log in "))
        self.signupbtn.setText(_translate("LoginPage", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QDialog()
    ui = Ui_LoginPage(LoginPage)
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
