# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_settings(object):
    def __init__(self,window):
        self.window=window

    def openlogin_signout(self):
        self.window.close()
        from ui_folder.login import Ui_LoginPage
        self.window= QtWidgets.QDialog()
        self.ui =Ui_LoginPage(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
    def loaddata(self):
        conn = sqlite3.connect("project")
        res = conn.execute("select * from users")
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(res):
            self.tableWidget.insertRow(row_number)
            for col_num, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, col_num, QtWidgets.QTableWidgetItem(str(data)))

        conn.close()
    def delete_data(self):
        name = self.uname.text()
        conn = sqlite3.connect("project")
        conn.execute("delete from users where username = ?",(name,))
        conn.commit()
        msg = QMessageBox()
        msg.setWindowTitle("Leaf Restaurant")
        msg.setText("The record successfully deleted!")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()
        conn.close()


    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(1116, 903)
        self.centralwidget = QtWidgets.QWidget(settings)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 901))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setLineWidth(1)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(150, 730, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.delete_2.setObjectName("delete_2")
        ##############################loading data ##################################
        self.delete_2.clicked.connect(self. delete_data)
        #############################################################################


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 201, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/top-left.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(910, 710, 201, 191))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/corner.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 730, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-color:gray;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        ##############################loading data ##################################
        self.pushButton_3.clicked.connect(self.loaddata)
        #############################################################################
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(300, 300, 561, 411))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.Dense4Pattern)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 5, item)
        self.signout = QtWidgets.QPushButton(self.centralwidget)
        self.signout.setGeometry(QtCore.QRect(1050, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.signout.setFont(font)
        self.signout.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border-radius: 25px !important;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #EEEEEE;\n"
"border-style:inset;\n"
"color: #0097A7;\n"
"\n"
"}")
        self.signout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/sign_out_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signout.setIcon(icon)
        self.signout.setIconSize(QtCore.QSize(40, 40))
        self.signout.setObjectName("signout")
        ##############################loading data ##################################
        self.signout.clicked.connect(self.openlogin_signout)
        #############################################################################
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 100, 131, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/users.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"color: #4DD0E1;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 40, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.uname = QtWidgets.QLineEdit(self.centralwidget)
        self.uname.setGeometry(QtCore.QRect(300, 730, 281, 51))
        font = QtGui.QFont()
        font.setFamily("red")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.uname.setFont(font)
        self.uname.setStyleSheet("QLineEdit{\n"
"border-radius : 25px;\n"
"border:3px solid #4DD0E1;\n"
"font: 15px red ;\n"
"padding-left: 10px;\n"
"}")
        self.uname.setObjectName("uname")
        settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "MainWindow"))
        self.delete_2.setText(_translate("settings", "Delete"))
        self.pushButton_3.setText(_translate("settings", "Load Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("settings", " User_ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("settings", "Email Address"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("settings", "Username"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("settings", "Password"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("settings", "Confirm_Password"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("settings", "LEAF "))
        self.label_6.setText(_translate("settings", "Restaurant Managemnet System "))
        self.label_7.setText(_translate("settings", "Users"))
        self.uname.setPlaceholderText(_translate("settings", "Username....."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings = QtWidgets.QMainWindow()
    ui = Ui_settings(settings)
    ui.setupUi(settings)
    settings.show()
    sys.exit(app.exec_())
